"""Add AppUser table

Revision ID: 9c6e78a16136
Revises: 
Create Date: 2025-05-05 00:34:15.235517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6e78a16136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appuser', schema=None) as batch_op:
        batch_op.drop_index('idx_appuser_email')

    with op.batch_alter_table('appuser_movie', schema=None) as batch_op:
        batch_op.drop_index('idx_appuser_movie_movie')
        batch_op.drop_index('idx_appuser_movie_user')
        batch_op.drop_constraint('fk_appuser_movie_appuser', type_='foreignkey')
        batch_op.drop_constraint('fk_appuser_movie_movie', type_='foreignkey')
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['movie_id'])
        batch_op.create_foreign_key(None, 'appuser', ['appuser_id'], ['appuser_id'])

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('genre_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=120),
               nullable=True)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_index('idx_movie_title')

    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_movie_genre_genre')
        batch_op.drop_index('idx_movie_genre_movie')
        batch_op.drop_constraint('fk_movie_genre_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_movie_genre_movie', type_='foreignkey')
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['movie_id'])
        batch_op.create_foreign_key(None, 'genre', ['genre_id'], ['genre_id'])

    with op.batch_alter_table('movie_language', schema=None) as batch_op:
        batch_op.alter_column('language_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('idx_movie_language_language')
        batch_op.drop_index('idx_movie_language_movie')
        batch_op.drop_constraint('fk_movie_lang_movie', type_='foreignkey')
        batch_op.drop_constraint('fk_movie_lang_language', type_='foreignkey')
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['movie_id'])
        batch_op.create_foreign_key(None, 'movielanguage', ['language_id'], ['language_id'])

    with op.batch_alter_table('movie_people', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_index('idx_movie_people_movie')
        batch_op.drop_index('idx_movie_people_people')
        batch_op.drop_constraint('fk_movie_people_people', type_='foreignkey')
        batch_op.drop_constraint('fk_movie_people_movie', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['people_id'])
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['movie_id'])

    with op.batch_alter_table('movielanguage', schema=None) as batch_op:
        batch_op.alter_column('language_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('people_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('people_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('movielanguage', schema=None) as batch_op:
        batch_op.alter_column('language_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('movie_people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_movie_people_movie', 'movie', ['movie_id'], ['movie_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_movie_people_people', 'people', ['people_id'], ['people_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_index('idx_movie_people_people', ['people_id'], unique=False)
        batch_op.create_index('idx_movie_people_movie', ['movie_id'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movie_language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_movie_lang_language', 'movielanguage', ['language_id'], ['language_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('fk_movie_lang_movie', 'movie', ['movie_id'], ['movie_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_index('idx_movie_language_movie', ['movie_id'], unique=False)
        batch_op.create_index('idx_movie_language_language', ['language_id'], unique=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('language_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_movie_genre_movie', 'movie', ['movie_id'], ['movie_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_movie_genre_genre', 'genre', ['genre_id'], ['genre_id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_index('idx_movie_genre_movie', ['movie_id'], unique=False)
        batch_op.create_index('idx_movie_genre_genre', ['genre_id'], unique=False)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index('idx_movie_title', ['title'], unique=False)

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('genre_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('appuser_movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_appuser_movie_movie', 'movie', ['movie_id'], ['movie_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_appuser_movie_appuser', 'appuser', ['appuser_id'], ['appuser_id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_index('idx_appuser_movie_user', ['appuser_id'], unique=False)
        batch_op.create_index('idx_appuser_movie_movie', ['movie_id'], unique=False)

    with op.batch_alter_table('appuser', schema=None) as batch_op:
        batch_op.create_index('idx_appuser_email', ['email'], unique=False)

    # ### end Alembic commands ###
